services:
  nginx-app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    # buile:
    #   context: ./nginx
    #   dockerfile: Dockerfile
    container_name: nginx-container
    port:
      - "80:80"
    volumes:
      - /home/ec2-user/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ec2-user/nginx/html:/usr/share/nginx/html
      - /home/ec2-user/nginx/logs:/var/log/nginx
    restart: always
    networks:
      - public-subnet
        aliases:
          - nginx-svc

networks:
  public-subnet:
    driver: bridge